data:
  # Configmaps
  springProfilesActive: "gcp"
  logLevel: "ERROR"
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  policyHost: "http://policy"
  indexerHost: "http://indexer"
  policyId: "osdu.instance.search"
  securityHttpsCertificateTrust: "true"
  # Deployments
  requestsCpu: "75m"
  requestsMemory: "448M"
  limitsCpu: "1"
  limitsMemory: "1G"
  serviceAccountName: "search"
  imagePullPolicy: "IfNotPresent"
  image: ""
  # redis connection. Change it if you want to use external redis
  redisSearchHost: ""
  redisSearchPort: 6379
  redisImage: "redis:7"
conf:
  appName: "search"
  elasticSecretName: "search-elastic-secret"
  onPremEnabled: false
  domain: ""
  searchRedisSecretName: "search-redis-secret"
istio:
  proxyCPU: "25m"
  proxyCPULimit: "200m"
  proxyMemory: "64Mi"
  proxyMemoryLimit: "256Mi"
