# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
      - README.md
      - .gitignore

pool:
  name: dps-build
  demands: maven

steps:
- task: Maven@3
  displayName: 'build, test, code coverage'
  inputs:
    mavenPomFile: 'pom.xml'
    options: '--settings ./search-core/maven/settings.xml -DVSTS_FEED_TOKEN=$(VSTS_FEED_TOKEN) -U'
    #testResultsFiles: '**/*/TEST-*.xml'
    #codeCoverageToolOption: JaCoCo
    goals: 'clean install'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'testing/integration-tests'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/search-integration-tests.zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder:
    Contents: |
     provider/search-byoc/target/*-spring-boot.jar
     provider/search-gcp/target/*-spring-boot.jar
     provider/search-gcp/src/main/appengine/app.yaml
     provider/search-gcp/src/main/resources/application.properties
     provider/search-gcp/scripts/deploy.sh
     provider/search-integration-tests.zip
    TargetFolder: '$(build.artifactstagingdirectory)'
    flattenFolders: true

- task: CopyFiles@2
  displayName: 'Copy Azure artifacts for maven deploy to: $(build.artifactstagingdirectory)'
  inputs:
    SourceFolder:
    Contents: |
      pom.xml
      provider/search-azure/maven/settings.xml
      provider/search-azure/pom.xml
      provider/search-azure/target/*-spring-boot.jar
    TargetFolder: '$(build.artifactstagingdirectory)'
    
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  condition: succeededOrFailed()
