apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.conf.configmap }}"
data:
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  JAVA_APP_JAR: "{{ .Values.data.javaAppJar }}"
  server.servlet.context-path: "{{ .Values.data.contextPath }}"
  server.port: "{{ .Values.data.serverPort }}"
  spring.main.allow-bean-definition-overriding: "{{ .Values.data.beanDefOverriding }}"
  ACCEPT_HTTP: "{{ .Values.data.acceptHttp }}"
  LOG_PREFIX: "{{ .Values.data.logPrefix }}"
  cache.expiration: "{{ .Values.data.cacheExpiration }}"
  cache.maxSize: "{{ .Values.data.cahceMaxSize }}"
  ibm.health-check-uri: "{{ .Values.data.healthCheckUri }}"
  logging.level.org.opengroup.osdu: "{{ .Values.data.loggingLevelOsdu }}"
  logging.level.org.springframework.web: "{{ .Values.data.loggingLevelSpring }}"
  AUTHORIZE_API: "http://{{ .Release.Name }}-ibm-entitlement-deploy:8080/api/entitlements/v2"
  DEPLOYMENT_ENVIRONMENT: "{{ .Values.data.deployEnv }}"
  ibm..db.url: "http://{{ .Release.Name }}-couchdb:5984"
  ibm.db.user: "{{ .Values.data.dbUser }}"
  ibm.env.prefix: "{{ .Values.data.envPrefix }}"
  ibm.env.prefix_project: "{{ .Values.data.envPrefixProject }}"
  ibm.keycloak.endpoint_url: "keycloak-discovery:8080"
  ibm.keycloak.realm: "{{ .Values.data.keycloakRealm }}"
  ibm.keycloak.useremail: "{{ .Values.data.keycloakUserEmail }}"
  ibm.db.password: "{{ .Values.data.dbPassw }}"
  PARTITION_API: "http://{{ .Release.Name }}-ibm-partition-deploy:8080/api/partition/v1"
  POLICY_API: "http://{{ .Release.Name }}-ibm-policy-deploy:8080/api/policy/v1"
  partition.keycloak.client_id: "{{ .Values.data.pKCClientId }}"
  partition.keycloak.client_secert: "{{ .Values.data.pKCClientSecret }}"
  partition.keycloak.grant_type: "{{ .Values.data.grantType }}"
  partition.keycloak.password: "{{ .Values.data.pKCPassword }}"
  partition.keycloak.realm: "{{ .Values.data.keycloakRealm }}"
  partition.keycloak.url: "{{ .Values.data.pKCEndPointHost }}"
  partition.keycloak.user: "{{ .Values.data.pKCUser }}"
  partition.keycloak.accept_http: "{{ .Values.data.pKAcceptHttp }}"
  tenantCache.exp.time.in.second: "{{ .Values.data.tenantCacheExpiryInSec }}"
  ibm.search.db.url: "http://{{ .Release.Name }}-couchdb:5984"
  ibm.search.db.user: "{{ .Values.data.dbUser }}"
  ibm.search.db.password: "{{ .Values.data.dbUser }}"
  ELASTIC_HOST: "{{ .Values.data.ibmElasticHost }}"	
  ELASTIC_PORT: "{{ .Values.data.ibmElasticPort }}"	
  ELASTIC_USER_PASSWORD: ""
  security.https.certificate.trust: "{{ .Values.data.ibmElasticSSLSecurity }}"
  service.policy.enabled: "{{ .Values.data.policServiceEnabled }}"
  osdu.entitlements.url: '${AUTHORIZE_API}'
  osdu.entitlement.url: '${AUTHORIZE_API}'
  PROVIDER_KEY: "{{ .Values.data.providerKey }}"
