{{- template "common.destinationrule" (list . "os-search.destinationrule") -}}
{{- define "os-search.destinationrule" -}}
## Define overrides for the service destination rule resource here
{{- end -}}