# Copyright © Amazon Web Services
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

AWSTemplateFormatVersion: 2010-09-09
Description: Creates all AWS resources used by OSDU's Search Service. Requires having previously setup the CodeCommit repository, as well as the CodePipeline (manual template).
Parameters:
  Environment:
    Description: The name of the environment.
    Type: String
    AllowedValues:
      - dev
      - uat
      - prod
    ConstraintDescription: Environment can only be "dev/uat/prod".
    Default: dev

  DeploymentRegion:
    Description: The AWS region to deploy the resources to.
    Type: String
    Default: us-east-1

  ApplicationName:
    Description: >
      The name of the application, should be equal to the repository name.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: os-search

  KeyName:
    Description: >
      Name of an existing EC2 KeyPair to enable SSH access to the ECS instances. Note that key pairs cannot
      be created through CloudFormation, but instead must be uploaded through the AWS Console.
    Type: AWS::EC2::KeyPair::KeyName
    Default: search-ecs-keypair

  DesiredCapacity:
    Description: The default number of instances to launch in the ECS cluster.
    Type: Number
    Default: '1'

  MinSize:
    Description: Minimum number of instances that can be launched in the ECS cluster.
    Type: Number
    Default: '1'

  MaxSize:
    Description: Maximum number of instances that can be launched in the ECS cluster.
    Type: Number
    Default: '1'

  InstanceType:
    Description: EC2 instance type
    Type: String
    Default: t3.large
    AllowedValues:
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
      - m5.12xlarge
      - m5.16xlarge
      - m5.24xlarge
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - t3.nano
      - t3.micro
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - t3.2xlarge
      - c5.large
      - c5.xlarge
      - c5.2xlarge
      - c5.4xlarge
      - c5.12xlarge
      - c5.16xlarge
      - c5.24xlarge
      - r5.large
      - r5.xlarge
      - r5.2xlarge
      - r5.4xlarge
      - r5.12xlarge
      - r5.24xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
      - i3.large
      - i3.xlarge
      - i3.2xlarge
      - i3.4xlarge
      - i3.10xlarge
      - i3.16xlarge
      - x1e.xlarge
      - x1e.2xlarge
      - x1e.4xlarge
      - x1e.8xlarge
      - x1e.16xlarge
      - x1e.32xlarge
    ConstraintDescription: Please choose a valid EC2 instance type for the ECS container instances.

  SearchServiceIamUsername:
    Description: The username of the service user for the OS Search Service.
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Type: String
    Default: service-user-os-search
    MinLength: '1'
    MaxLength: '64'

  SearchServiceIamKeyRotationSerial:
    Description: This integer value can only ever be incremented, and an increase in value results in a rotation of the user's access key.
    Type: Number
    Default: 1
  
  SNSTopicName:
    Description: >-
      The name of the Simple Notification Service topic for the OS Search Service. Defaults to osdu-search-messages.
      Will be prefixed with the environment name.
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: osdu-search-messages
    Type: String
    MinLength: '1'
    MaxLength: '64'

  SQSQueueName:
    Description: >-
      The name of the Simple Queue Service queue for the OS Search Service. Defaults to osdu-search-queue.
      Will be prefixed with the environment name.
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: osdu-search-queue
    Type: String
    MinLength: '1'
    MaxLength: '64'

  CursorCacheName:
    Description: The name of the cache cluster for the cursor cache. Will be prefixed with the environment name.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: searchCursorCache

  CursorCacheEngine:
    Description: Which caching platform to use for the cursor cache. Can be set to 'redis' or 'memcached'.
    Type: String
    AllowedValues:
      - redis
      - memcached
    ConstraintDescription: Can only be "redis" or "memcached"
    Default: redis

  CursorCacheNodeInstanceType:
    Description: The instance type for redis cache nodes for the cursor cache.
    ConstraintDescription: Must be a valid instance type from the list of allowed values.
    Default: cache.t2.micro
    AllowedValues:
      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
      - cache.m5.4xlarge
      - cache.m5.12xlarge
      - cache.m5.24xlarge
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.c1.xlarge
      - cache.r5.large
      - cache.r5.xlarge
      - cache.r5.2xlarge
      - cache.r5.4xlarge
      - cache.r5.12xlarge
      - cache.r5.24xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge
    Type: String

  CursorCacheNumberOfCacheNodes:
    Description: An integer value specifying the number of node in the redis cache for the cursor cache.
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 128
    
  IndexCacheName:
    Description: The name of the cache cluster for the index cache. Will be prefixed with the environment name.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: searchIndexCache

  IndexCacheEngine:
    Description: Which caching platform to use for the index cache. Can be set to 'redis' or 'memcached'.
    Type: String
    AllowedValues:
      - redis
      - memcached
    ConstraintDescription: Can only be "redis" or "memcached"
    Default: redis

  IndexCacheNodeInstanceType:
    Description: The instance type for redis cache nodes for the index cache.
    ConstraintDescription: Must be a valid instance type from the list of allowed values.
    Default: cache.t2.micro
    AllowedValues:
      - cache.m5.large
      - cache.m5.xlarge
      - cache.m5.2xlarge
      - cache.m5.4xlarge
      - cache.m5.12xlarge
      - cache.m5.24xlarge
      - cache.m4.large
      - cache.m4.xlarge
      - cache.m4.2xlarge
      - cache.m4.4xlarge
      - cache.m4.10xlarge
      - cache.t2.micro
      - cache.t2.small
      - cache.t2.medium
      - cache.c1.xlarge
      - cache.r5.large
      - cache.r5.xlarge
      - cache.r5.2xlarge
      - cache.r5.4xlarge
      - cache.r5.12xlarge
      - cache.r5.24xlarge
      - cache.r4.large
      - cache.r4.xlarge
      - cache.r4.2xlarge
      - cache.r4.4xlarge
      - cache.r4.8xlarge
      - cache.r4.16xlarge
    Type: String

  IndexCacheNumberOfCacheNodes:
    Description: An integer value specifying the number of node in the redis cache for the index cache.
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 128

  ECSPort:
    Description: The port that the ECS Service will listen on.
    Type: Number
    Default: 80
    MinValue: 1
    MaxValue: 65535

  ECSCPUAllocation:
    Description: The amount of CPU resources to allocate to each ECS task/container. Scale - 1024 = 1 vCPU core.
    Type: Number
    Default: 1024
    MinValue: 10
    MaxValue: 65535

  ECSMemoryAllocation:
    Description: The amount of memory (RAM) to allocate to each ECS task/container. Scale - 1 = 1MB of memory.
    Type: Number
    Default: 2048
    MinValue: 256
    MaxValue: 131072

  ElasticsearchPortNumber:
    Description: The port number to connect to the Elasticsearch
    Type: Number
    Default: 443

  DomainName:
    Description: >-
      The optional custom DNS name for the ECS service's load balancer. If omitted, the site will only be accessible
      via the ECS service's Application Load Balancer DNS name. This value is used in the creation and signing of
      the service's SSL certificate. Leave blank is not using a custom domain for this deployment.
    Type: String
    Default: ''

  HostedZoneName:
    Description: >-
      The name of the hosted zone (ex: for search.osdu.slb.com, this would likely be osdu.slb.com).
      Leave blank is not using a custom domain for this deployment.
    Type: String
    Default: ''

  AcmCertificateArn:
    Description: >-
      The Amazon Resource Name (ARN) of an existing AWS Certificate Manager (ACM) certificate.
      If omitted, a new SSL certified will be requested/generated (only if the custom domain name
      parameter is provided, otherwise the ECS service's ALB will not use SSL/HTTPS).
    Type: String
    AllowedPattern: "^(|arn:aws:acm:.*)$"
    Default: ''

  ElasticsearchDomainName:
    Description: The name of the Elasticsearch domain. Will be prefixed with the environment name.
    Type: String
    MinLength: '1'
    MaxLength: '64'
    AllowedPattern: "^[a-zA-Z]+[0-9a-zA-Z_-]*$"
    ConstraintDescription: Must start with a letter. Only numbers, letters, -, and _ accepted. Max. length 64 characters.
    Default: osdu-indexer

  VersionNumber:
    Description: The version number for the service jar being produced
    Type: String
    Default: '0.0.1'

  ServiceName:
    Description: >-
      The service name associated with the jar package for the Dockerfile.
    Type: String
    Default: 'search'

Resources:

  #### Shared Resources ################################################################

  IAMCredentialsStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
      - https://s3.amazonaws.com/${CloudFormationS3Bucket}/${ApplicationName}/Automated/${CFNTemplateFilename}
      - CloudFormationS3Bucket: !ImportValue
          'Fn::Sub': '${Environment}-S3BucketCloudFormation'
        CFNTemplateFilename: iam-credentials.yml
      Parameters:
        Environment: !Ref Environment
        Region: !Ref DeploymentRegion
        SearchServiceIamUsername: !Ref SearchServiceIamUsername
        SearchServiceIamKeyRotationSerial: !Ref SearchServiceIamKeyRotationSerial

  MessageBusSNSStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${CloudFormationS3Bucket}/${ApplicationName}/Automated/${CFNTemplateFilename}
        - CloudFormationS3Bucket: !ImportValue
            'Fn::Sub': '${Environment}-S3BucketCloudFormation'
          CFNTemplateFilename: sns-topic.yml
      Parameters:
        Environment: !Ref Environment
        Region: !Ref DeploymentRegion
        SNSTopicName: !Ref SNSTopicName
        SQSQueueName: !Ref SQSQueueName

  #### ECS Resources ###################################################################

  ECSNetworkStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: IAMCredentialsStack
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${CloudFormationS3Bucket}/${ApplicationName}/Automated/${CFNTemplateFilename}
        - CloudFormationS3Bucket: !ImportValue
            'Fn::Sub': '${Environment}-S3BucketCloudFormation'
          CFNTemplateFilename: ecs-network.yml
      Parameters:
        Environment: !Ref Environment
        Region: !Ref DeploymentRegion
        ApplicationName: !Ref ApplicationName
        ECSPort: !Ref ECSPort
        DomainName: !Ref DomainName
        AcmCertificateArn: !Ref AcmCertificateArn

  ECSClusterStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: [CursorCacheStack, IndexCacheStack]
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${CloudFormationS3Bucket}/${ApplicationName}/Automated/${CFNTemplateFilename}
        - CloudFormationS3Bucket: !ImportValue
            'Fn::Sub': '${Environment}-S3BucketCloudFormation'
          CFNTemplateFilename: ecs-cluster.yml
      Parameters:
        Environment: !Ref Environment
        Region: !Ref DeploymentRegion
        ApplicationName: !Ref ApplicationName
        KeyName: !Ref KeyName
        DesiredCapacity: !Ref DesiredCapacity
        MaxSize: !Ref MaxSize
        InstanceType: !Ref InstanceType
        CursorCacheName: !Ref CursorCacheName
        IndexCacheName: !Ref IndexCacheName
        ECSPort: !Ref ECSPort
        SNSTopicName: !Ref SNSTopicName
        ECSMemoryAllocation: !Ref ECSMemoryAllocation
        ElasticsearchPortNumber: !Ref ElasticsearchPortNumber
        DomainName: !Ref DomainName
        HostedZoneName: !Ref HostedZoneName
        ElasticsearchDomainName: !Ref ElasticsearchDomainName
        VersionNumber: !Ref VersionNumber
        ServiceName: !Ref ServiceName



  #### Caching Resources ###############################################################

  CursorCacheStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: ECSNetworkStack
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${CloudFormationS3Bucket}/${ApplicationName}/Automated/${CFNTemplateFilename}
        - CloudFormationS3Bucket: !ImportValue
            'Fn::Sub': '${Environment}-S3BucketCloudFormation'
          CFNTemplateFilename: cache.yml
      Parameters:
        Environment: !Ref Environment
        Region: !Ref DeploymentRegion
        ApplicationName: !Ref ApplicationName
        CacheName: !Ref CursorCacheName
        CacheEngine: !Ref CursorCacheEngine
        NodeInstanceType: !Ref CursorCacheNodeInstanceType
        NumberOfCacheNodes: !Ref CursorCacheNumberOfCacheNodes

  IndexCacheStack:
    Type: 'AWS::CloudFormation::Stack'
    DependsOn: ECSNetworkStack
    Properties:
      TemplateURL: !Sub
        - https://s3.amazonaws.com/${CloudFormationS3Bucket}/${ApplicationName}/Automated/${CFNTemplateFilename}
        - CloudFormationS3Bucket: !ImportValue
            'Fn::Sub': '${Environment}-S3BucketCloudFormation'
          CFNTemplateFilename: cache.yml
      Parameters:
        Environment: !Ref Environment
        Region: !Ref DeploymentRegion
        ApplicationName: !Ref ApplicationName
        CacheName: !Ref IndexCacheName
        CacheEngine: !Ref IndexCacheEngine
        NodeInstanceType: !Ref IndexCacheNodeInstanceType
        NumberOfCacheNodes: !Ref IndexCacheNumberOfCacheNodes
