# Default values for search configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  # common
  springProfilesActive: "gcp"
  logLevel: "INFO"
  redisGroupHost: "redis-group-master"
  redisSearchHost: "redis-search-master"
  entitlementsHost: "http://entitlements"
  partitionHost: "http://partition"
  policyHost: "http://policy"
  indexerHost: "http://indexer"
  policyId: "search"
  securityHttpsCertificateTrust: "true"
  # gcp
  googleAudiences: ""

conf:
  configmap: "search-config"
  appName: "search"
  onPremEnabled: false
