# Default values for search configmap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

data:
  log_level: "INFO"
  redis_group_host: "redis-group-master"
  redis_search_host: "redis-search-master"
  redis_search_port: "6379"
  entitlements_host: "http://entitlements"
  security_https_certificate_trust: "true"
  partition_host: "http://partition"
  policy_host: "http://policy"
  policy_id: "search"
  indexer_base_host: "http://indexer"
  # gcp
  googleAudiences: ""

conf:
  configmap: "search-config"
  app_name: "search"
  on_prem_enabled: false
