apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.appName | quote }}
  name: {{ .Values.conf.configmap | quote }}
  namespace: {{ .Release.Namespace | quote }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.data.springProfilesActive | quote }}
  LOG_LEVEL: {{ .Values.data.logLevel | quote }}
  REDIS_GROUP_HOST: {{ .Values.data.redisGroupHost | quote }}
  REDIS_SEARCH_HOST: {{ .Values.data.redisSearchHost  | quote }}
  ENTITLEMENTS_HOST: {{ .Values.data.entitlementsHost | quote }}
  SECURITY_HTTPS_CERTIFICATE_TRUST: {{ .Values.data.securityHttpsCertificateTrust | quote }}
  PARTITION_HOST: {{ .Values.data.partitionHost | quote }}
  POLICY_HOST: {{ .Values.data.policyHost | quote }}
  POLICY_ID: {{ .Values.data.policyId | quote }}
  INDEXER_BASE_HOST: {{ .Values.data.indexerHost | quote }}
