apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.conf.appName }}"
  name: "{{ .Values.conf.configmap }}"
  namespace: "{{ .Release.Namespace }}"
data:
  SPRING_PROFILES_ACTIVE: "{{ .Values.data.springProfilesActive }}"
  LOG_LEVEL: "{{ .Values.data.logLevel }}"
  REDIS_GROUP_HOST: "{{ .Values.data.redisGroupHost }}"
  REDIS_SEARCH_HOST: "{{ .Values.data.redisSearchHost }}"
  ENTITLEMENTS_HOST: "{{ .Values.data.entitlementsHost }}"
  SECURITY_HTTPS_CERTIFICATE_TRUST: "{{ .Values.data.securityHttpsCertificateTrust }}"
  PARTITION_HOST: "{{ .Values.data.partitionHost }}"
  POLICY_HOST: "{{ .Values.data.policyHost }}"
  POLICY_ID: "{{ .Values.data.policyId }}"
  INDEXER_BASE_HOST: "{{ .Values.data.indexerHost }}"
  SERVICE_POLICY_ENABLED: "{{ .Values.data.servicePolicyEnabled }}"
  {{- if not .Values.conf.onPremEnabled }}
  GOOGLE_AUDIENCES: "{{ .Values.data.googleAudiences }}"
  {{- end }}
