steps:
# deploy container image to GKE
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment-os-search-service.yml
      - --location=us-central1-c
      - --cluster=anthos-test